import { z } from "zod";

export const ENDPOINTS = {
  GetUserTransactions: z.object({
    result: z.string(),
  }),
  GetCopyCostings4: z.object({
    job_cost_method: z.string(),
    base_job_cost: z.number(),
    default_per_page_cost: z.number(),
    copy_line_costs: z.string(),
    per_job_attribute_costs: z.string(),
  }),
  GetCopyJobCost3: z.object({
    base_job_cost: z.number(),
    job_attribute_costs: z.number(),
    page_attribute_costs: z.number(),
  }),
  GetPrintJobDetails3: z.object({
    pages: z.number(),
    color_pages: z.number(),
    sheets: z.number(),
    cost: z.number(),
    job_attributes: z.string(),
  }),
  AddTerminal: z.object({
    result: z.string(),
  }),
  AddUser: z.object({}),
  AddUser2: z.object({}),
  AddUserGroup: z.object({}),
  ChangePassword: z.object({}),
  CheckPrintJobPassword: z.object({}),
  ConfigureSession: z.object({}),
  ConfigureSession2: z.object({}),
  ConfigureSession3: z.object({}),
  CreditUser: z.object({}),
  DeletePrintJob: z.object({}),
  DeletePrintJob2: z.object({}),
  DeleteReservation: z.object({}),
  DeleteTerminal: z.object({}),
  DeleteUser: z.object({}),
  DeleteUserGroup: z.object({}),
  FindCodes: z.object({ result: z.string() }),
  FindUserCodes: z.object({ result: z.string() }),
  FindUserCodes2: z.object({ result: z.string() }),
  FindUserCodes3: z.object({ result: z.string() }),
  FindUsers: z.object({ result: z.string() }),
  GetCodeDetails: z.object({ result: z.string() }),
  GetCodeDetails2: z.object({ result: z.string() }),
  GetCopyCostings: z.object({
    job_cost_method: z.string(),
    fixed_cost: z.number(),
    costings: z.string(),
  }),
  GetCopyCostings2: z.object({
    job_cost_method: z.string(),
    fixed_cost: z.number(),
    costings: z.string(),
  }),
  GetCopyCostings3: z.object({
    job_cost_method: z.string(),
    base_job_cost: z.number(),
    default_per_page_cost: z.number(),
    copy_line_costs: z.string(),
    per_job_attribute_costs: z.string(),
  }),
  GetCopyJobCost: z.object({ result: z.number() }),
  GetCopyJobCost2: z.object({
    base_job_cost: z.number(),
    job_attribute_costs: z.number(),
    page_attribute_costs: z.number(),
  }),
  GetFaxJobCost: z.object({ result: z.number() }),
  GetInitializationData: z.object({ result: z.string() }),
  GetJobCostMethod: z.object({
    fixed_cost: z.number(),
    costings: z.string(),
  }),
  GetJobCostMethod2: z.object({
    base_job_cost: z.number(),
    default_per_page_cost: z.number(),
    per_page_attribute_costs: z.string(),
    per_job_attribute_costs: z.string(),
  }),
  GetLicenseDetails: z.object({ result: z.string() }),
  GetPharosStation: z.object({
    station_detail: z.string(),
    config_data: z.string(),
  }),
  GetPharosStation2: z.object({ result: z.string() }),
  GetPharosStations: z.object({ result: z.string() }),
  GetPharosStations2: z.object({ result: z.string() }),
  GetPrintJobDetails: z.object({
    pages: z.number(),
    sheets: z.number(),
    cost: z.number(),
    job_attributes: z.string(),
  }),
  GetPrintJobDetails2: z.object({
    pages: z.number(),
    color_pages: z.number(),
    sheets: z.number(),
    cost: z.number(),
    job_attributes: z.string(),
  }),
  GetProductVersion: z.object({ result: z.string() }),
  GetProductVersion2: z.object({ result: z.string() }),
  GetSignUpConfig: z.object({
    max_pending_scheduled: z.number(),
    max_days_in_advance: z.number(),
    scheduled_timeout: z.number(),
    queued_timeout: z.number(),
  }),
  GetUserDetails: z.object({
    balance: z.number(),
    credit_limit: z.number(),
    alias: z.string(),
    first_names: z.string(),
    last_name: z.string(),
    discounts: z.string(),
    uses_cost_centers: z.number(),
    active: z.number(),
    id: z.string(),
    group: z.string(),
    purses: z.string(),
  }),
  GetUserDetails2: z.object({
    balance: z.number(),
    credit_limit: z.number(),
    alias: z.string(),
    first_names: z.string(),
    last_name: z.string(),
    discounts: z.string(),
    uses_cost_centers: z.number(),
    active: z.number(),
    id: z.string(),
    group: z.string(),
    purses: z.string(),
  }),
  GetUserDetails3: z.object({
    balance: z.number(),
    credit_limit: z.number(),
    alias: z.string(),
    first_names: z.string(),
    last_name: z.string(),
    discounts: z.string(),
    uses_cost_centers: z.number(),
    active: z.number(),
    can_print_color: z.number(),
    id: z.string(),
    group: z.string(),
    email: z.string(),
    custom1: z.string(),
    custom2: z.string(),
    purses: z.string(),
  }),
  GetUserDetails4: z.object({ result: z.string() }),
  GetUserDetailsByAlias: z.object({
    user_id: z.string(),
    balance: z.number(),
    credit_limit: z.number(),
    first_names: z.string(),
    last_name: z.string(),
    discounts: z.string(),
    uses_cost_centers: z.number(),
    active: z.number(),
    id: z.string(),
    group: z.string(),
    purses: z.string(),
  }),
  GetUserGroup: z.object({
    group_name: z.string(),
    discount_rate: z.string(),
  }),
  GetUserPermissions: z.object({ result: z.string() }),
  InitializeSession: z.object({
    session_id: z.string(),
    utc_time: z.string(),
  }),
  InitializeSession2: z.object({
    session_id: z.string(),
    utc_time: z.string(),
    utc_offset: z.string(),
    time_zone_name: z.string(),
  }),
  KeepUserLocked: z.object({}),
  LicenseRequest: z.object({}),
  ListBranches: z.object({ result: z.string() }),
  ListCategories: z.object({ result: z.string() }),
  ListDevices: z.object({ result: z.string() }),
  ListLastAnswers: z.object({ result: z.string() }),
  ListLocations: z.object({ result: z.string() }),
  ListPharosStations: z.object({ result: z.string() }),
  ListPrintJobs: z.object({ result: z.string() }),
  ListPrintJobs2: z.object({ result: z.string() }),
  ListPrintJobsForStation: z.object({ result: z.string() }),
  ListPrintJobsForStation2: z.object({ result: z.string() }),
  ListRecentUserCodes: z.object({ result: z.string() }),
  ListRecentUserCodes2: z.object({ result: z.string() }),
  ListRecentUserCodes3: z.object({ result: z.string() }),
  ListReservationsFor: z.object({ result: z.string() }),
  ListTerminals: z.object({ result: z.string() }),
  ListTypes: z.object({ result: z.string() }),
  ListUserCodes: z.object({ result: z.string() }),
  ListUserGroups: z.object({ result: z.string() }),
  ListXPortTerminals: z.object({ result: z.string() }),
  LockMFD: z.object({ result: z.string() }),
  LoginUser: z.object({
    access_level: z.string(),
    refer_id: z.string(),
  }),
  LoginUser2: z.object({ result: z.string() }),
  Online: z.object({}),
  Ping: z.object({}),
  QueueForPC: z.object({
    state: z.number(),
    pc: z.string(),
    expected_start: z.string(),
  }),
  QueueForPC2: z.object({
    state: z.number(),
    pc: z.string(),
    expected_start: z.string(),
  }),
  RaiseAlert: z.object({}),
  RecordCopyJob: z.object({}),
  RecordCopyJob2: z.object({}),
  RecordCustomTransaction: z.object({}),
  RecordCustomTransaction2: z.object({}),
  RecordCustomTransaction3: z.object({}),
  RecordFaxJob: z.object({}),
  RecordFaxJob2: z.object({}),
  RecordFaxJob3: z.object({}),
  RecordPrintJob: z.object({}),
  RecordPrintJob2: z.object({}),
  RecordScanJob: z.object({}),
  RecordScanJob2: z.object({}),
  ReleaseAndRecordPrintJob: z.object({ result: z.string() }),
  ReleaseAndRecordPrintJob2: z.object({ result: z.string() }),
  ReleaseAndRecordPrintJob3: z.object({ result: z.string() }),
  ReleaseAndRecordPrintJob4: z.object({ result: z.string() }),
  ReleasePrintJob: z.object({}),
  ReservePC: z.object({
    pc_name: z.string(),
    actual_start: z.string(),
    pc_description: z.string(),
  }),
  ReservePC2: z.object({
    pc_name: z.string(),
    actual_start: z.string(),
    pc_description: z.string(),
  }),
  RunSQL: z.object({ result: z.string() }),
  SearchAvailableTimes: z.object({ result: z.string() }),
  SetCopyLines: z.object({}),
  UnlockMFD: z.object({}),
  UnlockUser: z.object({}),
  UpdatePharosStationConfiguration: z.object({}),
  UpdatePharosStationConfiguration2: z.object({}),
  UpdateTerminal: z.object({}),
  UpdateTerminalType: z.object({}),
  UpdateUser: z.object({}),
  UpdateUser2: z.object({}),
  UpdateUserGroup: z.object({}),
  ValidateAttributes: z.object({ result: z.string() }),
  ValidateDeviceAccess: z.object({ result: z.number() }),
};
